services:
  backend:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "5777:5777"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5777
    networks:
      - app-network
  
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_db
    ports:
      - "5778:5432"
    networks:
      - app-network
    volumes:
      - catalog-postgres-data:/var/lib/postgresql/data


networks:
  app-network:

volumes:
  catalog-postgres-data: