services:
  backend:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "5777:5777"
    depends_on:
      - postgres
      - redis-users
      - redis-carts
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5777
    networks:
      - app-network
  
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main_db
    ports:
      - "5778:5432"
    networks:
      - app-network
    volumes:
      - catalog-postgres-data:/var/lib/postgresql/data

  redis-users:
    image: redis:7
    restart: always
    ports:
      - "5779:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  
  redis-carts:
    image: redis:7
    restart: always
    ports:
      - "5780:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
      
  redis-orders:
    image: redis:7
    restart: always
    ports:
      - "5781:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
networks:
  app-network:

volumes:
  catalog-postgres-data: