services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: always
    command:
      - "--configFile=/etc/traefik/static.yml"
    ports:
      - "5700:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Infrastructure/Traefik/static.yml:/etc/traefik/static.yml:ro
      - ./Infrastructure/Traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
  
  api-server:
    container_name: api-server
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "5777:5777"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5777
    networks:
      - app-network
  
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main_db
    ports:
      - "5778:5432"
    networks:
      - app-network
    volumes:
      - catalog-postgres-data:/var/lib/postgresql/data
  
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./Infrastructure/Nginx
      dockerfile: Dockerfile
    volumes:
      - ./Resources/ProductImages:/usr/share/nginx/static/images:ro
    networks:
      - app-network


networks:
  app-network:

volumes:
  catalog-postgres-data: